import 'raf/polyfill'
import 'setimmediate'
import './globals.css'

import { ReactNode } from 'react'
import { Provider } from 'app/provider'
import { StylesProvider } from './styles-provider'
import NPProvider from '../npprovider';
import WebLayout from "../../../packages/app/layout/web";

export const metadata = {
  title: 'Create Solito App',
  description: 'Generated by create Solito app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body className="scrollbar-thin scrollbar-thumb-[#0b7b0e] scrollbar-track-[#efcf37] scrollbar-thumb-rounded-full scrollbar-track-rounded-full h-32 overflow-y-scroll bg-gradient-to-r from-gray-300 to-[#c7dedc]">

        <WebLayout>
          <NPProvider>
            <StylesProvider>

              {children}
            </StylesProvider>

          </NPProvider>
        </WebLayout>



      </body>
    </html >
  )
}
